### PR TITLE
Add support for all CS functions as of 7.53

### PR DESCRIPTION
**Pull request by heydona**

### CODE REVIEW

**Comment by kuzyn** [comment]
Hiya @heydona 

Hope all is well and sunny! There seems to be more to this than just adding support for 7.53 functions, no?

**Comment by heydona** [comment]
It is bringing syntax highlighting to all CS functions/keywords just extending the words.
I've not changed any of the regexes (yet)

**Comment by kuzyn** [comment]
Ah, I think that my confusion comes from the mismatch of the `.YAML-tmlangage` files and the `.tmlanguage` files, I'll have a look whenever I get a chance

**Comment by kuzyn** [comment]
Better very late than never? ;)

https://github.com/kuzyn/chatscript-tmlanguage/releases/tag/1.3.0

On the bright side I (finally) took time to do decent tooling so all further contributions will be a whole lot smoother. All the best to you @heydona !

**Pull request closed without merging**
